Repository gardener/machine-controller-manager-provider-local, pull requests merged in 2024-03, with the labels that each got.

#30 Enable `dependabot` for node images
  .github/dependabot.yaml
Labels: needs/review, size/xs

#33 Remove `charts` folder from `make generate
  Makefile
Labels: reviewed/lgtm, size/xs

#34 Make repo compliant
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  cmd/machine-controller/main.go
  hack/tools.go
  pkg/api/v1alpha1/doc.go
  pkg/api/v1alpha1/provider_spec.go
  pkg/api/validation/validation.go
  pkg/local/create_machine.go
  pkg/local/delete_machine.go
  pkg/local/driver.go
  pkg/local/driver_test.go
  pkg/local/get_machine_status.go
  pkg/local/get_volume_ids.go
  pkg/local/list_machines.go
Labels: reviewed/lgtm, size/xl, area/ipcei

#37 Remove `nerdctl` workaround for local OS image
  node/Dockerfile
  node/docker
Labels: reviewed/lgtm, size/s
